FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json tailwind.config.js ./
COPY cmd/web/assets/css/input.css cmd/web/assets/css/

RUN npm install

VOLUME /app/cmd/web/assets/css

CMD ["npm", "run", "build"]
