FROM docker.io/library/golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/a-h/templ/cmd/templ@latest
COPY . .

RUN templ generate
RUN go build -o /app/server ./internal/server/main.go

FROM docker.io/library/golang:1.24

WORKDIR /app

COPY --from=builder /app/server /app/server
COPY cmd/web cmd/web

EXPOSE 8080

VOLUME /app/cmd/web/assets/css

CMD ["./app/server"]
