FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/a-h/templ/cmd/templ@latest
COPY . .

RUN templ generate && go build -o /app/server internal/sever/main.go

FROM golang:1.24-slim

WORKDIR /app

COPY --from=builder /app/server .
COPY cmd/web cmd/web

EXPOSE 8080

VOLUME /app/cmd/web/assets/css

CMD ["./server"]
