services:
  - type: web
    name: client
    env: docker
    dockerfilePath: ./client/Dockerfile
  
  - type: web
    name: server
    runtime: go
    rootDir: server
    buildCommand: go build -o app .
    startCommand: ./app
    dockerfilePath: ./server/Dockerfile
